<?php

return [
    'airports' => [
        [
            'id'   => 1,
            'name' => 'Casablanca',
        ],
        [
            'id'   => 2,
            'name' => 'Rabat-Salé',
        ],
        [
            'id'   => 3,
            'name' => 'Tanger',
        ],
        [
            'id'   => 4,
            'name' => 'Gare Tanger',
        ],
    ],
    'hotels'          => [
        ['id' => 1, 'name' => 'Mövenpick'],
        ['id' => 2, 'name' => 'Hilton'],
    ],
    'room_categories' => [
        ['id' => 1, 'name' => 'Standard', 'hotel_id' => 1],
        ['id' => 2, 'name' => 'Standard', 'hotel_id' => 2],
    ],
    'restorations' => [
        ['id' => 1, 'name' => 'Food court'],
        ['id' => 2, 'name' => 'Le Restaurant'],
        ['id' => 3, 'name' => 'Chapiteau VIP'],
    ],
    'participant'     => [
        'types' => [
            [
                'id'               => 1,
                'name'             => 'Standard',
                'group_id'         => 1,
                'restoration'      => 1,
                'hotel_id'         => null,
                'room_type'        => null,
                'room_category_id' => null,
            ],
            [
                'id'               => 2,
                'name'             => 'Premium sans hébergement',
                'restoration'      => 2,
                'hotel_id'         => null,
                'room_type'        => null,
                'room_category_id' => null,
                'group_id'         => 1,
            ],
            [
                'id'               => 3,
                'name'             => 'Premium avec hébergement',
                'restoration'      => 2,
                'hotel_id'         => null,
                'room_type'        => null,
                'room_category_id' => null,
                'group_id'         => 1,
            ],
            [
                'id'               => 4,
                'name'             => 'Speaker',
                'restoration'      => 2,
                'hotel_id'         => 1,
                'room_type'        => 1,
                'room_category_id' => 1,
                'group_id'         => 1,
            ],
            [
                'id'               => 5,
                'name'             => 'Conjoint',
                'group_id'         => 1,
                'restoration'      => null,
                'hotel_id'         => null,
                'room_type'        => null,
                'room_category_id' => null,
            ],
            [
                'id'               => 6,
                'name'             => 'Délégation',
                'restoration'      => 2,
                'hotel_id'         => 1,
                'room_type'        => 1,
                'room_category_id' => 1,
                'group_id'         => 1,
            ],
            [
                'id'               => 7,
                'name'             => 'Presse',
                'restoration'      => 1,
                'hotel_id'         => null,
                'room_type'        => null,
                'room_category_id' => null,
                'group_id'         => 2,
            ],
            [
                'id'               => 8,
                'name'             => 'Partenaire média',
                'restoration'      => 2,
                'room_type'        => 1,
                'hotel_id'         => 2,
                'room_category_id' => 2,
                'group_id'         => 2,
            ],
            [
                'id'               => 9,
                'name'             => 'Sponsor',
                'restoration'      => 2,
                'room_type'        => 1,
                'hotel_id'         => 2,
                'room_category_id' => 2,
                'group_id'         => 2,
            ],
            [
                'id'               => 10,
                'name'             => 'Organisateur',
                'restoration'      => 1,
                'hotel_id'         => null,
                'room_type'        => null,
                'room_category_id' => null,
                'group_id'         => 3,
            ],
            [
                'id'               => 11,
                'name'             => 'Institut Amadeus',
                'restoration'      => null,
                'hotel_id'         => null,
                'room_type'        => null,
                'room_category_id' => null,
                'group_id'         => 3,
            ],
            [
                'id'               => 12,
                'name'             => 'Police / Armée / Gendarmerie',
                'restoration'      => null,
                'hotel_id'         => null,
                'room_type'        => null,
                'room_category_id' => null,
                'group_id'         => 3,
            ],
            [
                'id'               => 13,
                'name'             => 'Sécurité',
                'restoration'      => null,
                'hotel_id'         => null,
                'room_type'        => null,
                'room_category_id' => null,
                'group_id'         => 3,
            ],
            [
                'id'               => 14,
                'name'             => 'Staff',
                'restoration'      => 3,
                'room_type'        => 1,
                'hotel_id'         => 2,
                'room_category_id' => 2,
                'group_id'         => 3,
            ],
        ],
    ],
]
?>